apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval
  labels:
    app: approval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approval
  template:
    metadata:
      labels:
        app: approval
    spec:
      containers:
        - name: approval
          image: admin16.azurecr.io/approval:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            #httpGet:
             # path: '/actuator/health'
             # port: 8080
            tcpSocket:
              port: 8081
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
